# Generated by Django 4.1 on 2022-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_order_email_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_order',
            field=models.CharField(default=4012, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
